-- ============================================================
-- PERMISOS POR DOCUMENTO / INVENTARIO
-- Sistema Inventarios - Supabase
--
-- Ejecutar una vez en Supabase > SQL Editor.
-- Esta migración agrega permisos por usuario y documento y
-- refuerza el acceso con Row Level Security (RLS).
-- ============================================================

create schema if not exists private;

-- ------------------------------------------------------------
-- 1. Identidad del creador del documento
-- ------------------------------------------------------------
alter table public.documentos
    add column if not exists creado_por uuid references auth.users(id);

alter table public.documentos
    alter column creado_por set default auth.uid();

-- ------------------------------------------------------------
-- 2. Tabla de permisos
-- ------------------------------------------------------------
create table if not exists public.documento_permisos (
    id bigint generated by default as identity primary key,
    documento_id bigint not null references public.documentos(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    puede_ver boolean not null default false,
    puede_agregar boolean not null default false,
    puede_modificar boolean not null default false,
    puede_importar boolean not null default false,
    puede_retirar boolean not null default false,
    puede_eliminar boolean not null default false,
    fecha_creacion timestamptz not null default now(),
    fecha_actualizacion timestamptz not null default now(),
    unique (documento_id, user_id)
);

create index if not exists documento_permisos_user_idx
    on public.documento_permisos(user_id);

create index if not exists documento_permisos_documento_idx
    on public.documento_permisos(documento_id);

-- ------------------------------------------------------------
-- 3. Funciones privadas para RLS
-- ------------------------------------------------------------
create or replace function private.usuario_es_administrador()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
    select exists (
        select 1
        from public.usuarios u
        where u.id = (select auth.uid())
          and u.activo = true
          and u.rol = 'administrador'
    );
$$;

create or replace function private.usuario_tiene_rol(p_rol text)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
    select exists (
        select 1
        from public.usuarios u
        where u.id = (select auth.uid())
          and u.activo = true
          and u.rol = p_rol
    );
$$;

create or replace function private.usuario_puede_documento(
    p_documento_id bigint,
    p_permiso text
)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
    select
        (select private.usuario_es_administrador())
        or exists (
            select 1
            from public.documento_permisos dp
            where dp.documento_id = p_documento_id
              and dp.user_id = (select auth.uid())
              and case p_permiso
                    when 'ver' then dp.puede_ver
                    when 'agregar' then dp.puede_agregar
                    when 'modificar' then dp.puede_modificar
                    when 'importar' then dp.puede_importar
                    when 'retirar' then dp.puede_retirar
                    when 'eliminar' then dp.puede_eliminar
                    else false
                  end
        );
$$;

revoke execute on function private.usuario_es_administrador() from public;
revoke execute on function private.usuario_tiene_rol(text) from public;
revoke execute on function private.usuario_puede_documento(bigint, text) from public;

grant usage on schema private to authenticated;
grant execute on function private.usuario_es_administrador() to authenticated;
grant execute on function private.usuario_tiene_rol(text) to authenticated;
grant execute on function private.usuario_puede_documento(bigint, text) to authenticated;

-- ------------------------------------------------------------
-- 4. Al crear un documento, el creador recibe todos los permisos.
-- ------------------------------------------------------------
create or replace function private.asignar_permisos_creador_documento()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.creado_por is not null then
        insert into public.documento_permisos (
            documento_id,
            user_id,
            puede_ver,
            puede_agregar,
            puede_modificar,
            puede_importar,
            puede_retirar,
            puede_eliminar
        )
        values (
            new.id,
            new.creado_por,
            true,
            true,
            true,
            true,
            true,
            true
        )
        on conflict (documento_id, user_id) do nothing;
    end if;
    return new;
end;
$$;

 drop trigger if exists trg_permisos_creador_documento on public.documentos;
create trigger trg_permisos_creador_documento
after insert on public.documentos
for each row execute function private.asignar_permisos_creador_documento();

revoke execute on function private.asignar_permisos_creador_documento() from public;

-- ------------------------------------------------------------
-- 5. RLS: tabla de permisos
-- ------------------------------------------------------------
alter table public.documento_permisos enable row level security;

revoke all on table public.documento_permisos from anon;
grant select, insert, update, delete on table public.documento_permisos to authenticated;

drop policy if exists documento_permisos_select on public.documento_permisos;
drop policy if exists documento_permisos_insert on public.documento_permisos;
drop policy if exists documento_permisos_update on public.documento_permisos;
drop policy if exists documento_permisos_delete on public.documento_permisos;

create policy documento_permisos_select
on public.documento_permisos
for select
to authenticated
using (
    user_id = (select auth.uid())
    or (select private.usuario_es_administrador())
);

create policy documento_permisos_insert
on public.documento_permisos
for insert
to authenticated
with check (
    (select private.usuario_es_administrador())
);

create policy documento_permisos_update
on public.documento_permisos
for update
to authenticated
using ((select private.usuario_es_administrador()))
with check ((select private.usuario_es_administrador()));

create policy documento_permisos_delete
on public.documento_permisos
for delete
to authenticated
using ((select private.usuario_es_administrador()));

-- ------------------------------------------------------------
-- 6. RLS: documentos
-- ------------------------------------------------------------
alter table public.documentos enable row level security;

grant select, insert, update, delete on public.documentos to authenticated;

-- Quitamos únicamente las políticas con los nombres que usa esta migración.
drop policy if exists documentos_permisos_select on public.documentos;
drop policy if exists documentos_permisos_insert on public.documentos;
drop policy if exists documentos_permisos_update on public.documentos;
drop policy if exists documentos_permisos_delete on public.documentos;

create policy documentos_permisos_select
on public.documentos
for select
to authenticated
using (
    (select private.usuario_puede_documento(id, 'ver'))
);

create policy documentos_permisos_insert
on public.documentos
for insert
to authenticated
with check (
    (select private.usuario_es_administrador())
    or (select private.usuario_tiene_rol('encargado'))
);

create policy documentos_permisos_update
on public.documentos
for update
to authenticated
using (
    (select private.usuario_puede_documento(id, 'modificar'))
    or (select private.usuario_puede_documento(id, 'importar'))
)
with check (
    (select private.usuario_puede_documento(id, 'modificar'))
    or (select private.usuario_puede_documento(id, 'importar'))
);

create policy documentos_permisos_delete
on public.documentos
for delete
to authenticated
using (
    (select private.usuario_puede_documento(id, 'eliminar'))
);

-- ------------------------------------------------------------
-- 7. RLS: documento_items
-- ------------------------------------------------------------
alter table public.documento_items enable row level security;

grant select, insert, update, delete on public.documento_items to authenticated;

drop policy if exists documento_items_permisos_select on public.documento_items;
drop policy if exists documento_items_permisos_insert on public.documento_items;
drop policy if exists documento_items_permisos_update on public.documento_items;
drop policy if exists documento_items_permisos_delete on public.documento_items;

create policy documento_items_permisos_select
on public.documento_items
for select
to authenticated
using (
    (select private.usuario_puede_documento(documento_id, 'ver'))
);

create policy documento_items_permisos_insert
on public.documento_items
for insert
to authenticated
with check (
    (select private.usuario_puede_documento(documento_id, 'importar'))
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
);

create policy documento_items_permisos_update
on public.documento_items
for update
to authenticated
using (
    (select private.usuario_puede_documento(documento_id, 'modificar'))
    or (select private.usuario_puede_documento(documento_id, 'agregar'))
    or (select private.usuario_puede_documento(documento_id, 'retirar'))
)
with check (
    (select private.usuario_puede_documento(documento_id, 'modificar'))
    or (select private.usuario_puede_documento(documento_id, 'agregar'))
    or (select private.usuario_puede_documento(documento_id, 'retirar'))
);

create policy documento_items_permisos_delete
on public.documento_items
for delete
to authenticated
using (
    (select private.usuario_puede_documento(documento_id, 'eliminar'))
);

-- ------------------------------------------------------------
-- 8. RLS: ajustes_stock
-- ------------------------------------------------------------
alter table public.ajustes_stock enable row level security;

grant select, insert, update, delete on public.ajustes_stock to authenticated;

drop policy if exists ajustes_documento_permisos_select on public.ajustes_stock;
drop policy if exists ajustes_documento_permisos_insert on public.ajustes_stock;
drop policy if exists ajustes_documento_permisos_update on public.ajustes_stock;
drop policy if exists ajustes_documento_permisos_delete on public.ajustes_stock;

create policy ajustes_documento_permisos_select
on public.ajustes_stock
for select
to authenticated
using (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'ver'))
);

create policy ajustes_documento_permisos_insert
on public.ajustes_stock
for insert
to authenticated
with check (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'agregar'))
    or (select private.usuario_puede_documento(documento_id, 'retirar'))
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
);

create policy ajustes_documento_permisos_update
on public.ajustes_stock
for update
to authenticated
using (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
)
with check (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
);

create policy ajustes_documento_permisos_delete
on public.ajustes_stock
for delete
to authenticated
using (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
    or (select private.usuario_puede_documento(documento_id, 'agregar'))
    or (select private.usuario_puede_documento(documento_id, 'retirar'))
);

-- ------------------------------------------------------------
-- 9. RLS: movimientos
-- ------------------------------------------------------------
alter table public.movimientos enable row level security;

grant select, insert on public.movimientos to authenticated;

drop policy if exists movimientos_documento_permisos_select on public.movimientos;
drop policy if exists movimientos_documento_permisos_insert on public.movimientos;

create policy movimientos_documento_permisos_select
on public.movimientos
for select
to authenticated
using (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'ver'))
);

create policy movimientos_documento_permisos_insert
on public.movimientos
for insert
to authenticated
with check (
    documento_id is null
    or (select private.usuario_puede_documento(documento_id, 'agregar'))
    or (select private.usuario_puede_documento(documento_id, 'retirar'))
    or (select private.usuario_puede_documento(documento_id, 'modificar'))
);

-- ------------------------------------------------------------
-- 10. Secuencia: asegurar que authenticated pueda insertar IDs
-- cuando corresponda a tablas identity/serial.
-- ------------------------------------------------------------
-- No se modifica ninguna secuencia existente: Supabase/Postgres
-- normalmente la administra mediante el DEFAULT de la columna.

-- ============================================================
-- FIN
-- ============================================================
