-- ============================================================
-- SOLICITUDES DE ACCESO DE USUARIOS
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- ============================================================

create table if not exists public.solicitudes_usuarios (
    id bigint generated by default as identity primary key,
    nombre text not null,
    email text not null,
    rol_solicitado text not null default 'consulta',
    estado text not null default 'pendiente',
    fecha_solicitud timestamptz not null default now(),
    revisado_por text,
    fecha_revision timestamptz,
    observaciones text,
    constraint solicitudes_usuarios_rol_check
        check (rol_solicitado in ('consulta', 'encargado')),
    constraint solicitudes_usuarios_estado_check
        check (estado in ('pendiente', 'aprobada', 'rechazada'))
);

create index if not exists idx_solicitudes_usuarios_estado
    on public.solicitudes_usuarios (estado, fecha_solicitud desc);

create index if not exists idx_solicitudes_usuarios_email
    on public.solicitudes_usuarios (lower(email));

-- Función usada por las políticas RLS para determinar si el usuario
-- autenticado es un administrador activo.
create or replace function public.usuario_es_administrador()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.usuarios u
        where u.id = auth.uid()
          and lower(coalesce(u.rol, '')) = 'administrador'
          and coalesce(u.activo, false) = true
    );
$$;

alter table public.solicitudes_usuarios enable row level security;

drop policy if exists solicitudes_insertar on public.solicitudes_usuarios;
create policy solicitudes_insertar
on public.solicitudes_usuarios
for insert
to anon, authenticated
with check (
    rol_solicitado in ('consulta', 'encargado')
    and estado = 'pendiente'
);

drop policy if exists solicitudes_consultar on public.solicitudes_usuarios;
create policy solicitudes_consultar
on public.solicitudes_usuarios
for select
to authenticated
using (public.usuario_es_administrador());

drop policy if exists solicitudes_actualizar on public.solicitudes_usuarios;
create policy solicitudes_actualizar
on public.solicitudes_usuarios
for update
to authenticated
using (public.usuario_es_administrador())
with check (
    estado in ('pendiente', 'aprobada', 'rechazada')
);

-- IMPORTANTE:
-- La tabla usuarios debe permitir que la aplicación cree el perfil inicial
-- inactivo durante una solicitud y que un administrador active/cambie el rol.
-- Si usuarios tiene RLS y actualmente bloquea estas operaciones, habrá que
-- agregar políticas equivalentes para esa tabla.
