-- ============================================================
-- SOLICITUDES DE ACCESO DE USUARIOS
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- ============================================================

create table if not exists public.solicitudes_usuarios (
    id bigint generated by default as identity primary key,
    nombre text not null,
    email text not null,
    rol_solicitado text not null default 'consulta',
    estado text not null default 'pendiente',
    fecha_solicitud timestamptz not null default now(),
    revisado_por text,
    fecha_revision timestamptz,
    observaciones text,
    constraint solicitudes_usuarios_rol_check
        check (rol_solicitado in ('consulta', 'encargado')),
    constraint solicitudes_usuarios_estado_check
        check (estado in ('pendiente', 'aprobada', 'rechazada'))
);

create index if not exists idx_solicitudes_usuarios_estado
    on public.solicitudes_usuarios (estado, fecha_solicitud desc);

create index if not exists idx_solicitudes_usuarios_email
    on public.solicitudes_usuarios (lower(email));

-- Si tu proyecto ya usa RLS, estas políticas permiten que el cliente
-- pueda crear una solicitud y que un usuario autenticado pueda consultar
-- las solicitudes. La aplicación además limita las acciones administrativas
-- al rol administrador.
alter table public.solicitudes_usuarios enable row level security;

drop policy if exists solicitudes_insertar on public.solicitudes_usuarios;
create policy solicitudes_insertar
on public.solicitudes_usuarios
for insert
to anon, authenticated
with check (
    rol_solicitado in ('consulta', 'encargado')
    and estado = 'pendiente'
);

drop policy if exists solicitudes_consultar on public.solicitudes_usuarios;
create policy solicitudes_consultar
on public.solicitudes_usuarios
for select
to authenticated
using (true);

drop policy if exists solicitudes_actualizar on public.solicitudes_usuarios;
create policy solicitudes_actualizar
on public.solicitudes_usuarios
for update
to authenticated
using (true)
with check (estado in ('pendiente', 'aprobada', 'rechazada'));

-- IMPORTANTE:
-- La tabla usuarios debe permitir que la aplicación cree el perfil inicial
-- inactivo durante una solicitud y que un administrador active/cambie el rol.
-- Si usuarios tiene RLS y actualmente bloquea estas operaciones, ajustaremos
-- sus políticas según el esquema que tengas en Supabase.
